---
title: "demo"
author: "JcB"
date: "07/09/2014"
output: html_document
---

source: http://rgeomatic.hypotheses.org/157

Voir le fichier __readme.mkd__.

```{r}

# librairies
library(RCurl)
library(RJSONIO)

# import de données
dataOrig<-read.csv("ville2.csv",sep=",")
dataDest<-read.csv("ville2.csv",sep=",")

# nombre d'origines et de destination
dOrig<-dim(dataOrig)[1]
dDest<-dim(dataDest)[1]

# creation de la matrice vide
req <-matrix(nrow=dOrig,ncol=dDest, dimnames=list(dataOrig$NOM,dataDest$NOM))

# création de la matrice des requêtes à envoyer
for (i in 1:dOrig){
  for (j in 1:dDest){
    req[i,j] <- paste("http://localhost:8989/route?point=",
                    paste(dataOrig$Y[i],dataOrig$X[i],sep=","),"&point=",
                    paste(dataDest$Y[j],dataDest$X[j],sep=","),
                    "&locale=fr&instructions=false&calc_points=false",sep="")
  }
}

# reception des requêtes
result<-apply(X=req,c(1,2),function(x) {try(getURL(URLencode(x) ),silent=TRUE)})

# fonction de parsage des réponses 

source("distancier.R")

mat<-apply(X=result,c(1,2), decode.temps)

# passage des milliseconde en minutes
mat<-round(mat/(1000*60),0)
mat

mat2<-apply(X=result,c(1,2), decode.distance)
mat2 <- round(mat2/1000,1)
mat2
```

Distance entre HTP et le CH Haguenau:

```{r}
source("distancier.R")
x1 <- 7.70714690 # HTP
y1 <- 48.59323950
x2 <- 7.77857800 # CH Haguenau
y2 <- 48.79733580
req1 <- paste("http://localhost:8989/route?point=", paste(y1, x1, sep=","), "&point=", paste(y2, x2, sep=","), "&locale=fr&instructions=false&calc_points=false",sep="")
t <- decode.temps(req1)
round(t/(1000*60), 0)
t <- decode.distance(req1)
t
```

Pour trouver des coordonnées manquantes:
```{}
library("ggmap")
geocode("Nouvel Hôpital Civil")

```
Information from URL : http://maps.googleapis.com/maps/api/geocode/json?address=Nouvel+H%c3%b4pital+Civil&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms
       lon      lat
1 7.742367 48.57501

